name: Run DogLang Tests

on:
  pull_request:
    branches:
      - '**'  # Run on PRs to any branch
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
      
      - name: Run tests
        run: |
          pytest tests/ -v